#!/bin/bash

MYDIR=`dirname $0`

# set up some tmp files because pasting from a fifo hangs open because the fifo gets no EOF
TMP1=$(mktemp)
TMP2=$(mktemp)
echo TMP1=$TMP1
echo TMP2=$TMP2

git log  --format=tformat:"%H~author_date~%ai~commiter_date~%ci" | \
awk 'BEGIN { FS = "~" } ; { print $1 " " $3 }' | \
$MYDIR/addToTime.sh | \
tee >( cut -d'~' -f1 > $TMP1) > >(cut -d'~' -f2 | sort -rn > $TMP2)

#join orig commitish list with reordered sorted time and pip to the 
# magic git history changer
paste -d' ' $TMP1 $TMP2 | $MYDIR/changeGitTime 

# tidy up //comment to debug
rm $TMP1
rm $TMP2
